# Generated by Django 4.0.5 on 2022-06-28 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=500, unique=True)),
                ('amount', models.IntegerField()),
                ('requirement', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500)),
                ('date_established', models.DateField()),
                ('motto', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('middle_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('superuser', 'superuser'), ('acountant', 'acountant'), ('teacher', 'teacher')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='', max_length=200)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('fees_status', models.CharField(choices=[('CLEARED', 'CLEARED'), ('ON ARRANGEMENT', 'ON ARRANGEMENT'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
                ('parent_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('enrolement', models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('march', 'march'), ('april', 'april'), ('may', 'may'), ('june', 'june'), ('july', 'july'), ('august', 'august'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec')], default='Jan', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(default='Grade R', on_delete=django.db.models.deletion.CASCADE, to='management.grade')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.month')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.gradeduration'),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.month'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('object', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
