# Generated by Django 4.0.5 on 2022-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='number_of_assets',
            field=models.CharField(default='', max_length=200),
        ),
    ]
