# Generated by Django 4.0.5 on 2022-06-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_asset_number_of_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset',
            new_name='SchoolAssets',
        ),
    ]
