# Generated by Django 4.0.5 on 2022-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_asset_schoolassets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(default='', max_length=200)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_cost', models.IntegerField(blank=True, null=True)),
                ('requested_by', models.CharField(default='', max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('permission_granted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=300, null=True)),
                ('reason', models.TextField(blank=True, max_length=200, null=True)),
                ('date_requested', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Expenses',
                'verbose_name_plural': 'School Expenses',
            },
        ),
        migrations.AlterModelOptions(
            name='schoolassets',
            options={'verbose_name': 'School Asset', 'verbose_name_plural': 'School Assets'},
        ),
    ]
