# Generated by Django 4.0.5 on 2022-06-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_schoolexpenses_alter_schoolassets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexpenses',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
