# Generated by Django 4.0.5 on 2022-06-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_schoolexpenses_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolexpenses',
            name='quantity',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
