# Generated by Django 4.0.5 on 2022-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_schoolexpenses_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolassets',
            name='asset_value',
            field=models.IntegerField(default='', max_length=200),
        ),
    ]
