# Generated by Django 4.0.5 on 2022-06-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_accountant_user_is_lecturer_user_is_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_lecturer',
            new_name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
