# Generated by Django 4.0.5 on 2022-06-28 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='', max_length=200)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_arrears', models.IntegerField()),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('current_arrears', models.IntegerField()),
                ('fees_status', models.CharField(choices=[('CLEARED', 'CLEARED'), ('ON ARRANGEMENT', 'ON ARRANGEMENT'), ('NOT PAID', 'NOT PAID')], default='NOT PAID', max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('year', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=300, null=True)),
                ('grade', models.ForeignKey(default='Grade R', on_delete=django.db.models.deletion.CASCADE, to='management.grade')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.month')),
            ],
        ),
        migrations.CreateModel(
            name='FeesParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('grade', models.ForeignKey(default='Grade R', on_delete=django.db.models.deletion.CASCADE, to='management.grade')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.month')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrailFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('item', models.TextField(max_length=300)),
                ('date', models.CharField(max_length=400)),
                ('page', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trail ',
            },
        ),
    ]
